const _qs = [
    'has fire in it',
    'is part of a psalm of David',
    'has Jesus\' favorite deciple in it',
    'is uplifting',
    'makes you laugh every time',
    'is about love',
    'has a woman in it',
    'has a sword in it',
    'is on the first page of your bible',
    'is on the last page of your bible',
    'is part of one of the letters from Paul',
    'is in Proverbs',
    'is about an arc',
    'is about worship',
    'you don\'t understand',
    'has some nice israelite family tree',
    'is about God\'s blessing',
    'has gold in it',
    'has silver in it',
    'has Jesus in it',
    'is in revelation',
    'has Jerusalem in it',
    'has a fight in it',
    'has a prophecy in it',
    'has horses in it',
    'has sheep in it',
    'mentions God\'s glory',
    'has words of Mose in it',
    'has Enoch in it',
    'has Elijah in it',
    'is the 150th',
    'mentions Holy Spirit',
    'tells someone to not be afraid',
    'mentions the church',
    'talks about power',
    'has "verily, verily" in it',
    'has fish in it',
    'mentions city walls',
    'mentions a cave',
]

export const questions: IQuestion[] = _qs.map(text => ({asked: false, text})); 
